### ISSUE TITLE
write generator script

### ISSUE THREAD

**Issue by shahidcodes** [shahidcodes/sariejs#1]
Write generator script to create a tempestjs project using [this repo](https://github.com/shahidcodes/tempest-example) as base.

**Comment by medimessarat** [comment]
Hello, i'd like to start working on it, so we want to make a script so that it creates temptJs project for us right?

**Comment by shahidcodes** [comment]
The goal here to make a cli script like create-react-app or express-generator so we can create a project by running `tempestjs create appname`
